### ISSUE TITLE
Mapping/equivalences cross language

### ISSUE THREAD

**Issue by ljwolf** [JosiahParry/sfdep#1]
Hi! Co-maintainer of esda here. I'm not as well versed as @rsbivand here, but I think that the [mappings between packages might need some duplication?](https://github.com/JosiahParry/sfdep/blob/3c246b712469a1e3b09aca64ad87b1ff4b14735a/vignettes/spdep-and-pysal.Rmd#L36)

This arises because `esda` is "object-oriented" in its design... so its estimators compute & store a variety of statistics in a single pass. For example, in the `G_Local` class, we compute Z-scores their corresponding p-values  (like those returned by `spdep::localG`) and store them in the `.Zs` and `.p_norm` attributes, respectively. We also, by default, compute the conditional permutation p-values `p_sim` using 999 replications, akin to `spdep::localG_perm`. So, the "cognate" in `esda` is `G_Local` for both `spdep::localG` and `spdep::localG_perm`. When we expose new inference versions, we'll probably just add them to the objects, too, if their computational cost is simple. That is, at least until we decide upon the next-generation interface, which is a GSOC project this year. 

I could be misunderstanding how the cognate table is intended (or, indeed, what the equivalences are!) but it'd be useful to clarify.

**Comment by JosiahParry** [comment]
Helpful! So in the example of `local_g` the pysal equivalent would be `G.Local.Gs`? As that is where the returned value is stored?

**Comment by ljwolf** [comment]
Yep, I believe so!

**Comment by JosiahParry** [comment]
Done! I _think_ everything is up to snuff.
