### ISSUE TITLE
Inefficient calculation of bivariate moran

### ISSUE THREAD

**Issue by JosiahParry** [JosiahParry/sfdep#28]
https://github.com/JosiahParry/sfdep/blob/45f8e539aba745358549497f70a335cf4f76f540/R/local-moran-bv-impl.R#L15

This calculation of the bivariate local moran is slow. It would be much more effecitve to calculate using `x * st_lag(y, nb, wt)`. See benchmark below. 

This can be replaced fairly simply. After changing `local_moran_bv_calc()` to include `nb` argument, `local_moran_bv_impl()` and `local_moran_bv_perm_impl()` will need to be modified to use the new calculation.

``` r
library(sfdep)

x <- guerry_nb$crime_pers
y <- guerry_nb$wealth
nb <- guerry_nb$nb
wt <- guerry_nb$wt

bench::mark(
  current = sfdep:::local_moran_bv_calc(x, find_xj(y, nb), wt),
  simpler = x * st_lag(y, nb, wt)
)
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 current     107.5µs  115.6µs     8327.      24KB     16.7
#> 2 simpler      17.1µs   18.1µs    53472.     107KB     10.7
```

<sup>Created on 2022-08-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by opelolo** [comment]
Hi @JosiahParry please assign this to me. I'd love to give it a try. Thank you

**Comment by opelolo** [comment]
Claimed. I will work on it right away. Thank you

**Comment by JosiahParry** [comment]
@opelolo awesome! 

For the function definition in line 15, I'd suggest the arguments to be `x`, `y`, `nb`, and `wt`. Then the body of the function can be `x * st_lag(y, nb, wt)`. Then, update the instances where `local_moran_bv_calc()` is called

**Comment by JosiahParry** [comment]
Closed in https://github.com/JosiahParry/sfdep/pull/29
